package com.recall.app.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors - Based on Material Design 3 Color Tokens
val md_theme_light_primary = Color(0xFF2C5BB6)
val md_theme_light_onPrimary = Color(0xFFF9F8FF)
val md_theme_light_primaryContainer = Color(0xFFA8C0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF003887)
val md_theme_light_primaryFixed = Color(0xFFA8C0FF)
val md_theme_light_onPrimaryFixed = Color(0xFF00245D)
val md_theme_light_primaryFixedDim = Color(0xFF92B2FF)
val md_theme_light_onPrimaryFixedVariant = Color(0xFF004099)
val md_theme_light_primaryDim = Color(0xFF1B4FA9)

val md_theme_light_secondary = Color(0xFF006975)
val md_theme_light_onSecondary = Color(0xFFECFCFF)
val md_theme_light_secondaryContainer = Color(0xFF98F0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF005B65)
val md_theme_light_secondaryFixed = Color(0xFF98F0FF)
val md_theme_light_onSecondaryFixed = Color(0xFF00464F)
val md_theme_light_secondaryFixedDim = Color(0xFF58E7FB)
val md_theme_light_onSecondaryFixedVariant = Color(0xFF006571)
val md_theme_light_secondaryDim = Color(0xFF005C67)

val md_theme_light_tertiary = Color(0xFF6834EB)
val md_theme_light_onTertiary = Color(0xFFFDF7FF)
val md_theme_light_tertiaryContainer = Color(0xFFC0ADFF)
val md_theme_light_onTertiaryContainer = Color(0xFF3E00A6)
val md_theme_light_tertiaryFixed = Color(0xFFC0ADFF)
val md_theme_light_onTertiaryFixed = Color(0xFF25006C)
val md_theme_light_tertiaryFixedDim = Color(0xFFB39CFF)
val md_theme_light_onTertiaryFixedVariant = Color(0xFF4700BD)
val md_theme_light_tertiaryDim = Color(0xFF5C20DF)

val md_theme_light_error = Color(0xFFAC3434)
val md_theme_light_onError = Color(0xFFFFF7F6)
val md_theme_light_errorContainer = Color(0xFFF56965)
val md_theme_light_onErrorContainer = Color(0xFF65000B)
val md_theme_light_errorDim = Color(0xFF70030F)

val md_theme_light_background = Color(0xFFF8F9FA)
val md_theme_light_onBackground = Color(0xFF2E3335)

val md_theme_light_surface = Color(0xFFF8F9FA)
val md_theme_light_onSurface = Color(0xFF2E3335)
val md_theme_light_surfaceVariant = Color(0xFFDEE3E5)
val md_theme_light_onSurfaceVariant = Color(0xFF5A6062)
val md_theme_light_surfaceTint = Color(0xFF2C5BB6)
val md_theme_light_inverseSurface = Color(0xFF0C0F10)
val md_theme_light_inverseOnSurface = Color(0xFF9B9D9E)

val md_theme_light_outline = Color(0xFF767C7E)
val md_theme_light_outlineVariant = Color(0xFFAEB3B5)

val md_theme_light_surfaceBright = Color(0xFFF8F9FA)
val md_theme_light_surfaceDim = Color(0xFFD5DBDD)
val md_theme_light_surfaceContainer = Color(0xFFEBEEF0)
val md_theme_light_surfaceContainerLow = Color(0xFFF2F4F5)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerHigh = Color(0xFFE5E9EB)
val md_theme_light_surfaceContainerHighest = Color(0xFFDEE3E5)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF92B2FF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF1B4FA9)
val md_theme_dark_onPrimaryContainer = Color(0xFFA8C0FF)
val md_theme_dark_primaryFixed = Color(0xFFA8C0FF)
val md_theme_dark_onPrimaryFixed = Color(0xFF00245D)
val md_theme_dark_primaryFixedDim = Color(0xFF92B2FF)
val md_theme_dark_onPrimaryFixedVariant = Color(0xFF004099)
val md_theme_dark_primaryDim = Color(0xFF1B4FA9)

val md_theme_dark_secondary = Color(0xFF58E7FB)
val md_theme_dark_onSecondary = Color(0xFF00353B)
val md_theme_dark_secondaryContainer = Color(0xFF004F59)
val md_theme_dark_onSecondaryContainer = Color(0xFF98F0FF)
val md_theme_dark_secondaryFixed = Color(0xFF98F0FF)
val md_theme_dark_onSecondaryFixed = Color(0xFF00464F)
val md_theme_dark_secondaryFixedDim = Color(0xFF58E7FB)
val md_theme_dark_onSecondaryFixedVariant = Color(0xFF006571)
val md_theme_dark_secondaryDim = Color(0xFF005C67)

val md_theme_dark_tertiary = Color(0xFFB39CFF)
val md_theme_dark_onTertiary = Color(0xFF3A0099)
val md_theme_dark_tertiaryContainer = Color(0xFF4F15C7)
val md_theme_dark_onTertiaryContainer = Color(0xFFC0ADFF)
val md_theme_dark_tertiaryFixed = Color(0xFFC0ADFF)
val md_theme_dark_onTertiaryFixed = Color(0xFF25006C)
val md_theme_dark_tertiaryFixedDim = Color(0xFFB39CFF)
val md_theme_dark_onTertiaryFixedVariant = Color(0xFF4700BD)
val md_theme_dark_tertiaryDim = Color(0xFF5C20DF)

val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_errorDim = Color(0xFF70030F)

val md_theme_dark_background = Color(0xFF0C0F10)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)

val md_theme_dark_surface = Color(0xFF0C0F10)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF2E3335)
val md_theme_dark_onSurfaceVariant = Color(0xFFAEB3B5)
val md_theme_dark_surfaceTint = Color(0xFF92B2FF)
val md_theme_dark_inverseSurface = Color(0xFFF8F9FA)
val md_theme_dark_inverseOnSurface = Color(0xFF5A6062)

val md_theme_dark_outline = Color(0xFF767C7E)
val md_theme_dark_outlineVariant = Color(0xFF4A4F51)

val md_theme_dark_surfaceBright = Color(0xFF2E3335)
val md_theme_dark_surfaceDim = Color(0xFF0C0F10)
val md_theme_dark_surfaceContainer = Color(0xFF1A1C1E)
val md_theme_dark_surfaceContainerLow = Color(0xFF141618)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0A0C0D)
val md_theme_dark_surfaceContainerHigh = Color(0xFF242628)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2E3335)
